In [11]:
import numpy as np
import random
from random import choice

ones = [-1, 1]
size = 4
matrix1 = np.array([[choice(ones) for i in range(size)] for j in range(size)])
sum1 = 0
for i in range(size):
    for j in range(size-1):
        sum1 += matrix1[i][j]*matrix1[i][j+1]
    sum1 += matrix1[i][size-1]*matrix1[i][0]
    
    matrix_transpose = np.transpose(matrix1)
    sum2 = 0
    for k in range(size):
        for m in range(size-1):
            sum2 += matrix_transpose[k][m]*matrix_transpose[k][m+1]
        sum2 += matrix_transpose[k][size-1]*matrix_transpose[k][0]
print(matrix1)

sum=sum1+sum2
print(sum)

[[-1  1  1  1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1  1  1 -1]]
-8
